/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku_try;
import java.awt.Font; 
import javax.swing.JOptionPane;

/**
 *
 * @author Ramesh
 */
public class NewJFrame extends javax.swing.JFrame {

    static int[][] sudoku = new int[9][9];
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        r1c1 = new javax.swing.JTextField();
        r1c3 = new javax.swing.JTextField();
        r1c2 = new javax.swing.JTextField();
        r1c6 = new javax.swing.JTextField();
        r1c4 = new javax.swing.JTextField();
        r1c5 = new javax.swing.JTextField();
        r1c8 = new javax.swing.JTextField();
        r1c7 = new javax.swing.JTextField();
        r1c9 = new javax.swing.JTextField();
        r2c3 = new javax.swing.JTextField();
        r2c1 = new javax.swing.JTextField();
        r2c5 = new javax.swing.JTextField();
        r2c4 = new javax.swing.JTextField();
        r2c6 = new javax.swing.JTextField();
        r2c2 = new javax.swing.JTextField();
        r2c7 = new javax.swing.JTextField();
        r2c8 = new javax.swing.JTextField();
        r2c9 = new javax.swing.JTextField();
        r4c3 = new javax.swing.JTextField();
        r4c4 = new javax.swing.JTextField();
        r4c6 = new javax.swing.JTextField();
        r4c1 = new javax.swing.JTextField();
        r4c5 = new javax.swing.JTextField();
        r3c3 = new javax.swing.JTextField();
        r3c1 = new javax.swing.JTextField();
        r3c5 = new javax.swing.JTextField();
        r3c4 = new javax.swing.JTextField();
        r3c6 = new javax.swing.JTextField();
        r3c2 = new javax.swing.JTextField();
        r3c7 = new javax.swing.JTextField();
        r3c8 = new javax.swing.JTextField();
        r4c9 = new javax.swing.JTextField();
        r4c8 = new javax.swing.JTextField();
        r3c9 = new javax.swing.JTextField();
        r4c2 = new javax.swing.JTextField();
        r4c7 = new javax.swing.JTextField();
        r6c3 = new javax.swing.JTextField();
        r6c4 = new javax.swing.JTextField();
        r6c6 = new javax.swing.JTextField();
        r6c1 = new javax.swing.JTextField();
        r6c5 = new javax.swing.JTextField();
        r5c3 = new javax.swing.JTextField();
        r5c1 = new javax.swing.JTextField();
        r5c5 = new javax.swing.JTextField();
        r5c4 = new javax.swing.JTextField();
        r5c6 = new javax.swing.JTextField();
        r5c2 = new javax.swing.JTextField();
        r5c7 = new javax.swing.JTextField();
        r5c8 = new javax.swing.JTextField();
        r8c7 = new javax.swing.JTextField();
        r8c2 = new javax.swing.JTextField();
        r7c9 = new javax.swing.JTextField();
        r8c8 = new javax.swing.JTextField();
        r8c9 = new javax.swing.JTextField();
        r7c8 = new javax.swing.JTextField();
        r7c7 = new javax.swing.JTextField();
        r7c2 = new javax.swing.JTextField();
        r7c5 = new javax.swing.JTextField();
        r7c6 = new javax.swing.JTextField();
        r7c4 = new javax.swing.JTextField();
        r7c1 = new javax.swing.JTextField();
        r7c3 = new javax.swing.JTextField();
        r8c5 = new javax.swing.JTextField();
        r8c1 = new javax.swing.JTextField();
        r8c6 = new javax.swing.JTextField();
        r8c4 = new javax.swing.JTextField();
        r8c3 = new javax.swing.JTextField();
        r6c9 = new javax.swing.JTextField();
        r6c8 = new javax.swing.JTextField();
        r5c9 = new javax.swing.JTextField();
        r6c2 = new javax.swing.JTextField();
        r6c7 = new javax.swing.JTextField();
        r9c8 = new javax.swing.JTextField();
        r9c9 = new javax.swing.JTextField();
        r9c7 = new javax.swing.JTextField();
        r9c2 = new javax.swing.JTextField();
        r9c6 = new javax.swing.JTextField();
        r9c4 = new javax.swing.JTextField();
        r9c5 = new javax.swing.JTextField();
        r9c1 = new javax.swing.JTextField();
        r9c3 = new javax.swing.JTextField();
        results = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       
        r1c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c1FocusLost(evt);
            }
        });

        
        r1c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c2FocusLost(evt);
            }
        });


        r1c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c3FocusLost(evt);
            }
        });

        r1c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c6FocusLost(evt);
            }
        });

        r1c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c4FocusLost(evt);
            }
        });

        r1c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c5FocusLost(evt);
            }
        });

        r1c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c8FocusLost(evt);
            }
        });

        r1c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c7FocusLost(evt);
            }
        });

        r1c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r1c9FocusLost(evt);
            }
        });

        r2c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c3FocusLost(evt);
            }
        });

        r2c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c1FocusLost(evt);
            }
        });

        r2c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c5FocusLost(evt);
            }
        });

        r2c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c4FocusLost(evt);
            }
        });

        r2c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c6FocusLost(evt);
            }
        });

        r2c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c2FocusLost(evt);
            }
        });

        r2c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c7FocusLost(evt);
            }
        });

        r2c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c8FocusLost(evt);
            }
        });

        r2c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r2c9FocusLost(evt);
            }
        });

        r4c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c3FocusLost(evt);
            }
        });

        r4c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c4FocusLost(evt);
            }
        });

        r4c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c6FocusLost(evt);
            }
        });

        r4c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c1FocusLost(evt);
            }
        });

        r4c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c5FocusLost(evt);
            }
        });

        r3c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c3FocusLost(evt);
            }
        });

        r3c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c1FocusLost(evt);
            }
        });

        r3c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c5FocusLost(evt);
            }
        });

        r3c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c4FocusLost(evt);
            }
        });

        r3c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c6FocusLost(evt);
            }
        });

        r3c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c2FocusLost(evt);
            }
        });

        r3c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c7FocusLost(evt);
            }
        });

        r3c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c8FocusLost(evt);
            }
        });

        r4c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c9FocusLost(evt);
            }
        });

        r4c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c8FocusLost(evt);
            }
        });

        r3c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r3c9FocusLost(evt);
            }
        });

        r4c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c2FocusLost(evt);
            }
        });

        r4c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r4c7FocusLost(evt);
            }
        });

        r6c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c3FocusLost(evt);
            }
        });

        r6c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c4FocusLost(evt);
            }
        });

        r6c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c6FocusLost(evt);
            }
        });

        r6c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c1FocusLost(evt);
            }
        });

        r6c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c5FocusLost(evt);
            }
        });

        r5c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c3FocusLost(evt);
            }
        });

        r5c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c1FocusLost(evt);
            }
        });

        r5c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c5FocusLost(evt);
            }
        });

        r5c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c4FocusLost(evt);
            }
        });

        r5c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c6FocusLost(evt);
            }
        });

        r5c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c2FocusLost(evt);
            }
        });

        r5c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c7FocusLost(evt);
            }
        });

        r5c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c8FocusLost(evt);
            }
        });

        r8c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c7FocusLost(evt);
            }
        });

        r8c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c2FocusLost(evt);
            }
        });

        r7c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c9FocusLost(evt);
            }
        });

        r8c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c8FocusLost(evt);
            }
        });

        r8c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c9FocusLost(evt);
            }
        });

        r7c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c8FocusLost(evt);
            }
        });

        r7c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c7FocusLost(evt);
            }
        });

        r7c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c2FocusLost(evt);
            }
        });

        r7c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c5FocusLost(evt);
            }
        });

        r7c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c6FocusLost(evt);
            }
        });

        r7c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c4FocusLost(evt);
            }
        });

        r7c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c1FocusLost(evt);
            }
        });

        r7c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r7c3FocusLost(evt);
            }
        });

        r8c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c5FocusLost(evt);
            }
        });

        r8c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c1FocusLost(evt);
            }
        });

        r8c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c6FocusLost(evt);
            }
        });

        r8c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c4FocusLost(evt);
            }
        });

        r8c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r8c3FocusLost(evt);
            }
        });

        r6c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c9FocusLost(evt);
            }
        });

        r6c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c8FocusLost(evt);
            }
        });

        r5c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r5c9FocusLost(evt);
            }
        });

        r6c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c2FocusLost(evt);
            }
        });

        r6c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r6c7FocusLost(evt);
            }
        });

        r9c8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c8FocusLost(evt);
            }
        });

        r9c9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c9FocusLost(evt);
            }
        });

        r9c7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c7FocusLost(evt);
            }
        });

        r9c2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c2FocusLost(evt);
            }
        });

        r9c6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c6FocusLost(evt);
            }
        });

        r9c4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c4FocusLost(evt);
            }
        });

        r9c5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c5FocusLost(evt);
            }
        });

        r9c1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c1FocusLost(evt);
            }
        });

        r9c3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                r9c3FocusLost(evt);
            }
        });
        

        results.setForeground(new java.awt.Color(204, 51, 0));
        results.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(results, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(r2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(r2c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(r3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r3c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(r4c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r4c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(r6c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r6c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(r5c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r5c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(r7c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r7c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(r8c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(r8c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r9c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r9c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(r1c9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(results, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r1c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r2c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r2c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r3c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r3c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r4c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r4c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r5c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r5c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r6c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r6c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r7c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r7c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r8c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r8c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r9c1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(r9c9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        r1c1.setFont(new Font("Arial",Font.BOLD, 35));
        r1c3.setFont(new Font("Arial",Font.BOLD, 35));
        r1c4.setFont(new Font("Arial",Font.BOLD, 35));
        r1c5.setFont(new Font("Arial",Font.BOLD, 35));
        r1c6.setFont(new Font("Arial",Font.BOLD, 35));
        r1c7.setFont(new Font("Arial",Font.BOLD, 35));
        r1c8.setFont(new Font("Arial",Font.BOLD, 35));
        r1c9.setFont(new Font("Arial",Font.BOLD, 35));

        r2c1.setFont(new Font("Arial",Font.BOLD, 35));
        r2c2.setFont(new Font("Arial",Font.BOLD, 35));
        r2c3.setFont(new Font("Arial",Font.BOLD, 35));
        r2c4.setFont(new Font("Arial",Font.BOLD, 35));
        r2c5.setFont(new Font("Arial",Font.BOLD, 35));
        r2c6.setFont(new Font("Arial",Font.BOLD, 35));
        r2c7.setFont(new Font("Arial",Font.BOLD, 35));
        r2c8.setFont(new Font("Arial",Font.BOLD, 35));
        r2c9.setFont(new Font("Arial",Font.BOLD, 35));

        r3c1.setFont(new Font("Arial",Font.BOLD, 35));
        r3c2.setFont(new Font("Arial",Font.BOLD, 35));
        r3c3.setFont(new Font("Arial",Font.BOLD, 35));
        r3c4.setFont(new Font("Arial",Font.BOLD, 35));
        r3c5.setFont(new Font("Arial",Font.BOLD, 35));
        r3c6.setFont(new Font("Arial",Font.BOLD, 35));
        r3c7.setFont(new Font("Arial",Font.BOLD, 35));
        r3c8.setFont(new Font("Arial",Font.BOLD, 35));
        r3c9.setFont(new Font("Arial",Font.BOLD, 35));

        r4c1.setFont(new Font("Arial",Font.BOLD, 35));
        r4c2.setFont(new Font("Arial",Font.BOLD, 35));
        r4c3.setFont(new Font("Arial",Font.BOLD, 35));
        r4c4.setFont(new Font("Arial",Font.BOLD, 35));
        r4c5.setFont(new Font("Arial",Font.BOLD, 35));
        r4c6.setFont(new Font("Arial",Font.BOLD, 35));
        r4c7.setFont(new Font("Arial",Font.BOLD, 35));
        r4c8.setFont(new Font("Arial",Font.BOLD, 35));
        r4c9.setFont(new Font("Arial",Font.BOLD, 35));

        r4c1.setFont(new Font("Arial",Font.BOLD, 35));
        r4c2.setFont(new Font("Arial",Font.BOLD, 35));
        r4c3.setFont(new Font("Arial",Font.BOLD, 35));
        r4c4.setFont(new Font("Arial",Font.BOLD, 35));
        r4c5.setFont(new Font("Arial",Font.BOLD, 35));
        r4c6.setFont(new Font("Arial",Font.BOLD, 35));
        r4c7.setFont(new Font("Arial",Font.BOLD, 35));
        r4c8.setFont(new Font("Arial",Font.BOLD, 35));
        r4c9.setFont(new Font("Arial",Font.BOLD, 35));

        r5c1.setFont(new Font("Arial",Font.BOLD, 35));
        r5c2.setFont(new Font("Arial",Font.BOLD, 35));
        r5c3.setFont(new Font("Arial",Font.BOLD, 35));
        r5c4.setFont(new Font("Arial",Font.BOLD, 35));
        r5c5.setFont(new Font("Arial",Font.BOLD, 35));
        r5c6.setFont(new Font("Arial",Font.BOLD, 35));
        r5c7.setFont(new Font("Arial",Font.BOLD, 35));
        r5c8.setFont(new Font("Arial",Font.BOLD, 35));
        r5c9.setFont(new Font("Arial",Font.BOLD, 35));

        r6c1.setFont(new Font("Arial",Font.BOLD, 35));
        r6c2.setFont(new Font("Arial",Font.BOLD, 35));
        r6c3.setFont(new Font("Arial",Font.BOLD, 35));
        r6c4.setFont(new Font("Arial",Font.BOLD, 35));
        r6c5.setFont(new Font("Arial",Font.BOLD, 35));
        r6c6.setFont(new Font("Arial",Font.BOLD, 35));
        r6c7.setFont(new Font("Arial",Font.BOLD, 35));
        r6c8.setFont(new Font("Arial",Font.BOLD, 35));
        r6c9.setFont(new Font("Arial",Font.BOLD, 35));

        r7c1.setFont(new Font("Arial",Font.BOLD, 35));
        r7c2.setFont(new Font("Arial",Font.BOLD, 35));
        r7c3.setFont(new Font("Arial",Font.BOLD, 35));
        r7c4.setFont(new Font("Arial",Font.BOLD, 35));
        r7c5.setFont(new Font("Arial",Font.BOLD, 35));
        r7c6.setFont(new Font("Arial",Font.BOLD, 35));
        r7c7.setFont(new Font("Arial",Font.BOLD, 35));
        r7c8.setFont(new Font("Arial",Font.BOLD, 35));
        r7c9.setFont(new Font("Arial",Font.BOLD, 35));

        r8c1.setFont(new Font("Arial",Font.BOLD, 35));
        r8c2.setFont(new Font("Arial",Font.BOLD, 35));
        r8c3.setFont(new Font("Arial",Font.BOLD, 35));
        r8c4.setFont(new Font("Arial",Font.BOLD, 35));
        r8c5.setFont(new Font("Arial",Font.BOLD, 35));
        r8c6.setFont(new Font("Arial",Font.BOLD, 35));
        r8c7.setFont(new Font("Arial",Font.BOLD, 35));
        r8c8.setFont(new Font("Arial",Font.BOLD, 35));
        r8c9.setFont(new Font("Arial",Font.BOLD, 35));

        r9c1.setFont(new Font("Arial",Font.BOLD, 35));
        r9c2.setFont(new Font("Arial",Font.BOLD, 35));
        r9c3.setFont(new Font("Arial",Font.BOLD, 35));
        r9c4.setFont(new Font("Arial",Font.BOLD, 35));
        r9c5.setFont(new Font("Arial",Font.BOLD, 35));
        r9c6.setFont(new Font("Arial",Font.BOLD, 35));
        r9c7.setFont(new Font("Arial",Font.BOLD, 35));
        r9c8.setFont(new Font("Arial",Font.BOLD, 35));
        r9c9.setFont(new Font("Arial",Font.BOLD, 35));
        r1c2.setFont(new Font("Arial",Font.BOLD, 35));
        results.setFont(new Font("Arial",Font.PLAIN, 35));
        

        pack();
    }// </editor-fold>//GEN-END:initComponents
        

        private void r1c1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r1c1FocusLost
        String text = r1c1.getText();
            if(text.equals("1") || text.equals("2") || text.equals("3") || text.equals("4") || text.equals("5") || text.equals("6") || text.equals("7") || text.equals("8") || text.equals("9")){
                sudoku[0][0] = Integer.parseInt(text);
            }
            else{
                JOptionPane.showMessageDialog( null,"Wrong Input. Type a number from 1-9" );
            }
        
    }//GEN-LAST:event_r1c1FocusLost

    private void r1c2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_r1c2FocusLost
        String text = r1c2.getText();        
        sudoku[0][1] = Integer.parseInt(text);
    }//GEN-LAST:event_r1c2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        submit();
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void r1c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c3.getText();        
        sudoku[0][2] = Integer.parseInt(text);
    }                                                                        

    private void r1c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c6.getText();        
        sudoku[0][5] = Integer.parseInt(text);
    }                                    

    private void r1c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c4.getText();        
        sudoku[0][3] = Integer.parseInt(text);
    }                                    

    private void r1c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c5.getText();        
        sudoku[0][4] = Integer.parseInt(text);
    }                                    

    private void r1c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c8.getText();        
        sudoku[0][7] = Integer.parseInt(text);
    }                                    

    private void r1c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c7.getText();        
        sudoku[0][6] = Integer.parseInt(text);
    }                                    

    private void r1c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r1c9.getText();        
        sudoku[0][8] = Integer.parseInt(text);
    }                                    

    private void r2c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c3.getText();        
        sudoku[1][2] = Integer.parseInt(text);
    }                                    

    private void r2c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c1.getText();        
        sudoku[1][0] = Integer.parseInt(text);
    }                                    

    private void r2c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c5.getText();        
        sudoku[1][4] = Integer.parseInt(text);
    }                                    

    private void r2c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c4.getText();        
        sudoku[1][3] = Integer.parseInt(text);
    }                                    

    private void r2c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c6.getText();        
        sudoku[1][5] = Integer.parseInt(text);
    }                                    

    private void r2c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c2.getText();        
        sudoku[1][1] = Integer.parseInt(text);
    }                                    

    private void r2c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c7.getText();        
        sudoku[1][6] = Integer.parseInt(text);
    }                                    

    private void r2c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c8.getText();        
        sudoku[1][7] = Integer.parseInt(text);
    }                                    

    private void r2c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r2c9.getText();        
        sudoku[1][8] = Integer.parseInt(text);
    }                                    

    private void r4c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c3.getText();        
        sudoku[3][2] = Integer.parseInt(text);
    }                                    

    private void r4c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c4.getText();        
        sudoku[3][3] = Integer.parseInt(text);
    }                                    

    private void r4c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c6.getText();        
        sudoku[3][5] = Integer.parseInt(text);
    }                                    

    private void r4c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c1.getText();        
        sudoku[3][0] = Integer.parseInt(text);
    }                                    

    private void r4c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c5.getText();        
        sudoku[3][4] = Integer.parseInt(text);
    }                                    

    private void r3c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c3.getText();        
        sudoku[2][2] = Integer.parseInt(text);
    }                                    

    private void r3c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c1.getText();        
        sudoku[2][0] = Integer.parseInt(text);
    }                                    

    private void r3c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c5.getText();        
        sudoku[2][4] = Integer.parseInt(text);
    }                                    

    private void r3c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c4.getText();        
        sudoku[2][3] = Integer.parseInt(text);
    }                                    

    private void r3c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c6.getText();        
        sudoku[2][5] = Integer.parseInt(text);
    }                                    

    private void r3c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c2.getText();        
        sudoku[2][1] = Integer.parseInt(text);
    }                                    

    private void r3c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c7.getText();        
        sudoku[2][6] = Integer.parseInt(text);
    }                                    

    private void r3c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c8.getText();        
        sudoku[2][7] = Integer.parseInt(text);
    }                                    

    private void r4c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c9.getText();        
        sudoku[3][8] = Integer.parseInt(text);
    }                                    

    private void r4c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c8.getText();        
        sudoku[3][7] = Integer.parseInt(text);
    }                                    

    private void r3c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r3c9.getText();        
        sudoku[2][8] = Integer.parseInt(text);
    }                                    

    private void r4c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c2.getText();        
        sudoku[3][1] = Integer.parseInt(text);
    }                                    

    private void r4c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r4c7.getText();        
        sudoku[3][6] = Integer.parseInt(text);
    }                                    

    private void r6c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c3.getText();        
        sudoku[5][2] = Integer.parseInt(text);
    }                                    

    private void r6c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c4.getText();        
        sudoku[5][3] = Integer.parseInt(text);
    }                                    

    private void r6c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c6.getText();        
        sudoku[5][5] = Integer.parseInt(text);
    }                                    

    private void r6c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c1.getText();        
        sudoku[5][0] = Integer.parseInt(text);
    }                                    

    private void r6c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c5.getText();        
        sudoku[5][4] = Integer.parseInt(text);
    }                                    

    private void r5c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c3.getText();        
        sudoku[4][2] = Integer.parseInt(text);
    }                                    

    private void r5c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c1.getText();        
        sudoku[4][0] = Integer.parseInt(text);
    }                                    

    private void r5c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c5.getText();        
        sudoku[4][4] = Integer.parseInt(text);
    }                                    

    private void r5c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c4.getText();        
        sudoku[4][3] = Integer.parseInt(text);
    }                                    

    private void r5c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c6.getText();        
        sudoku[4][5] = Integer.parseInt(text);
    }                                    

    private void r5c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c2.getText();        
        sudoku[4][1] = Integer.parseInt(text);
    }                                    

    private void r5c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c7.getText();        
        sudoku[4][6] = Integer.parseInt(text);
    }                                    

    private void r5c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c8.getText();        
        sudoku[4][7] = Integer.parseInt(text);
    }                                    

    private void r8c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c7.getText();        
        sudoku[7][6] = Integer.parseInt(text);
    }                                    

    private void r8c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c2.getText();        
        sudoku[7][1] = Integer.parseInt(text);
    }                                    

    private void r7c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c9.getText();        
        sudoku[6][8] = Integer.parseInt(text);
    }                                    

    private void r8c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c8.getText();        
        sudoku[7][7] = Integer.parseInt(text);
    }                                    

    private void r8c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c9.getText();        
        sudoku[7][8] = Integer.parseInt(text);
    }                                    

    private void r7c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c8.getText();        
        sudoku[6][7] = Integer.parseInt(text);
    }                                    

    private void r7c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c7.getText();        
        sudoku[6][6] = Integer.parseInt(text);
    }                                    

    private void r7c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c2.getText();        
        sudoku[6][1] = Integer.parseInt(text);
    }                                    

    private void r7c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c5.getText();        
        sudoku[6][4] = Integer.parseInt(text);
    }                                    

    private void r7c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c6.getText();        
        sudoku[6][5] = Integer.parseInt(text);
    }                                    

    private void r7c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c4.getText();        
        sudoku[6][3] = Integer.parseInt(text);
    }                                    

    private void r7c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c1.getText();        
        sudoku[6][0] = Integer.parseInt(text);
    }                                    

    private void r7c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r7c3.getText();        
        sudoku[6][2] = Integer.parseInt(text);
    }                                    

    private void r8c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c5.getText();        
        sudoku[7][4] = Integer.parseInt(text);
    }                                    

    private void r8c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c1.getText();        
        sudoku[7][0] = Integer.parseInt(text);
    }                                    

    private void r8c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c6.getText();        
        sudoku[7][5] = Integer.parseInt(text);
    }                                    

    private void r8c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c4.getText();        
        sudoku[7][3] = Integer.parseInt(text);
    }                                    

    private void r8c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r8c3.getText();        
        sudoku[7][2] = Integer.parseInt(text);
    }                                    

    private void r6c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c9.getText();        
        sudoku[5][8] = Integer.parseInt(text);
    }                                    

    private void r6c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c8.getText();        
        sudoku[5][7] = Integer.parseInt(text);
    }                                    

    private void r5c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r5c9.getText();        
        sudoku[4][8] = Integer.parseInt(text);
    }                                    

    private void r6c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c2.getText();        
        sudoku[5][1] = Integer.parseInt(text);
    }                                    

    private void r6c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r6c7.getText();        
        sudoku[5][6] = Integer.parseInt(text);
    }                                    

    private void r9c8FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c8.getText();        
        sudoku[8][7] = Integer.parseInt(text);
    }                                    

    private void r9c9FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c9.getText();        
        sudoku[8][8] = Integer.parseInt(text);
    }                                    

    private void r9c7FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c7.getText();        
        sudoku[8][6] = Integer.parseInt(text);
    }                                    

    private void r9c2FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c2.getText();        
        sudoku[8][1] = Integer.parseInt(text);
    }                                    

    private void r9c6FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c6.getText();        
        sudoku[8][5] = Integer.parseInt(text);
    }                                    

    private void r9c4FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c4.getText();        
        sudoku[8][3] = Integer.parseInt(text);
    }                                    

    private void r9c5FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c5.getText();        
        sudoku[8][4] = Integer.parseInt(text);
    }                                    

    private void r9c1FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c1.getText();        
        sudoku[8][0] = Integer.parseInt(text);
    }                                    

    private void r9c3FocusLost(java.awt.event.FocusEvent evt) {                                     
        String text = r9c3.getText();        
        sudoku[8][2] = Integer.parseInt(text);
    }
    
    public void submit(){
        outerloop:
        for(int i =0; i<9; i++){
            for(int j=0; j<9; j++){
                for(int k=1; k<9; k++){
                    if(j==k){
                        continue;
                    }
                    if(sudoku[i][j]==sudoku[i][k]){
                        results.setText("Sorry. You Lost");
                        break outerloop;
                    }
                    else{
                        continue;
                    }
                }    
            }
            if(i==8){
                        results.setText("Congratulations... You Won!!!");
            }
        }
        for(int a=0;a<9;a++){
            for(int b=0;b<9;b++){
                System.out.print(sudoku[a][b]+" ");
            }
            System.out.println("");
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField r1c1;
    private javax.swing.JTextField r1c2;
    private javax.swing.JTextField r1c3;
    private javax.swing.JTextField r1c4;
    private javax.swing.JTextField r1c5;
    private javax.swing.JTextField r1c6;
    private javax.swing.JTextField r1c7;
    private javax.swing.JTextField r1c8;
    private javax.swing.JTextField r1c9;
    private javax.swing.JTextField r2c1;
    private javax.swing.JTextField r2c2;
    private javax.swing.JTextField r2c3;
    private javax.swing.JTextField r2c4;
    private javax.swing.JTextField r2c5;
    private javax.swing.JTextField r2c6;
    private javax.swing.JTextField r2c7;
    private javax.swing.JTextField r2c8;
    private javax.swing.JTextField r2c9;
    private javax.swing.JTextField r3c1;
    private javax.swing.JTextField r3c2;
    private javax.swing.JTextField r3c3;
    private javax.swing.JTextField r3c4;
    private javax.swing.JTextField r3c5;
    private javax.swing.JTextField r3c6;
    private javax.swing.JTextField r3c7;
    private javax.swing.JTextField r3c8;
    private javax.swing.JTextField r3c9;
    private javax.swing.JTextField r4c1;
    private javax.swing.JTextField r4c2;
    private javax.swing.JTextField r4c3;
    private javax.swing.JTextField r4c4;
    private javax.swing.JTextField r4c5;
    private javax.swing.JTextField r4c6;
    private javax.swing.JTextField r4c7;
    private javax.swing.JTextField r4c8;
    private javax.swing.JTextField r4c9;
    private javax.swing.JTextField r5c1;
    private javax.swing.JTextField r5c2;
    private javax.swing.JTextField r5c3;
    private javax.swing.JTextField r5c4;
    private javax.swing.JTextField r5c5;
    private javax.swing.JTextField r5c6;
    private javax.swing.JTextField r5c7;
    private javax.swing.JTextField r5c8;
    private javax.swing.JTextField r5c9;
    private javax.swing.JTextField r6c1;
    private javax.swing.JTextField r6c2;
    private javax.swing.JTextField r6c3;
    private javax.swing.JTextField r6c4;
    private javax.swing.JTextField r6c5;
    private javax.swing.JTextField r6c6;
    private javax.swing.JTextField r6c7;
    private javax.swing.JTextField r6c8;
    private javax.swing.JTextField r6c9;
    private javax.swing.JTextField r7c1;
    private javax.swing.JTextField r7c2;
    private javax.swing.JTextField r7c3;
    private javax.swing.JTextField r7c4;
    private javax.swing.JTextField r7c5;
    private javax.swing.JTextField r7c6;
    private javax.swing.JTextField r7c7;
    private javax.swing.JTextField r7c8;
    private javax.swing.JTextField r7c9;
    private javax.swing.JTextField r8c1;
    private javax.swing.JTextField r8c2;
    private javax.swing.JTextField r8c3;
    private javax.swing.JTextField r8c4;
    private javax.swing.JTextField r8c5;
    private javax.swing.JTextField r8c6;
    private javax.swing.JTextField r8c7;
    private javax.swing.JTextField r8c8;
    private javax.swing.JTextField r8c9;
    private javax.swing.JTextField r9c1;
    private javax.swing.JTextField r9c2;
    private javax.swing.JTextField r9c3;
    private javax.swing.JTextField r9c4;
    private javax.swing.JTextField r9c5;
    private javax.swing.JTextField r9c6;
    private javax.swing.JTextField r9c7;
    private javax.swing.JTextField r9c8;
    private javax.swing.JTextField r9c9;
    private javax.swing.JLabel results;
    // End of variables declaration//GEN-END:variables
}
