/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.LoopyPlanetChallenge;

import javax.swing.JOptionPane;
import java.awt.Font;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import sun.audio.*;

/**
 *
 * @author Ramesh
 */
public class LoopyPlanetChallenge extends javax.swing.JFrame {

    /**
     * Creates new form LoopyPlanetChallenge
     */
    public LoopyPlanetChallenge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 255, 211));
        setBounds(new java.awt.Rectangle(0, 0, 600, 600));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Jupiter-icon.png"))); // NOI18N
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Mars-icon.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Mercury.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Neptune-icon.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Pluto-icon.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Saturn-icon.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Uranus.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/Venus-icon.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setText("Jupiter");

        jLabel11.setText("Mars");

        jLabel12.setText("Mercury");

        jLabel13.setText("Neptune");

        jLabel14.setText("Pluto");

        jLabel15.setText("Saturn");

        jLabel16.setText("Uranus");

        jLabel17.setText("Venus");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(" Click On A Planet And Enter Your Weight.");

        jButton1.setText("Exit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new Font("Serif",Font.BOLD,15));
        jLabel19.setForeground(new java.awt.Color(204, 0, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel14)
                                .addGap(108, 108, 108)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addGap(109, 109, 109)
                                .addComponent(jLabel17)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel10)
                                .addGap(110, 110, 110)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel13)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jButton1)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jLabel18.setFont(new Font("Arial",Font.BOLD, 24));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Jupiter.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(1);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Mars.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(2);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Mercury.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(3);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Neptune.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(4);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Pluto.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(5);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Saturn.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(6);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Uranus.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(7);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Venus.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(8);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Thank.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      System.exit(0);
    }
    }//GEN-LAST:event_jButton1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/WrongOption.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        runOption(10);
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //Shows the menu first 
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoopyPlanetChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoopyPlanetChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoopyPlanetChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoopyPlanetChallenge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoopyPlanetChallenge().setVisible(true);
            }
        });
         InputStream in;
        try{
           in=new FileInputStream(new File ("Start.wav"));
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
    }
    
    public  void runOption(int option){
        if(option>0 && option<9){
            runWeight(option);
        }
        else {
            jLabel19.setText("Please click on any planet icon.");
        }
    }
    
    public  void runWeight(int option){
        float weight;
        String WeightInput;
        WeightInput= JOptionPane.showInputDialog("Enter your weight on earth:");
        weight = Float.parseFloat(WeightInput);
        if(weight>0 && weight<500){
            switch (option){
                case 1:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*2.64 + " pounds on Jupiter.");
                    break;
                case 2:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*0.38 + " pounds on Mars");
                    break;
                case 3:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*0.37 + " pounds on Mercury");
                    break;
                case 4:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*1.12 + " pounds on Neptune");
                    break;
                case 5:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*0.04 + " pounds on Pluto");
                   break;
                case 6:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*1.15 + " pounds on Saturn");
                    break;
                case 7:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*1.15 + " pounds on Uranus");
                   break;
                case 8:
                    jLabel19.setText("Your Weight of " + weight + " on Earth would be " + weight*0.88 + " pounds on Venus");
                   break;                  
            }
            }
        else if(weight<0){
             InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Weight.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        jLabel19.setText("No one has negative weight. Be Reasonable");
            runWeight(option);
        }
        else{
             InputStream in;
        try{
           in=getClass().getResourceAsStream("/Audios/Weight.wav");
           AudioStream audios;
            audios = new AudioStream(in);
            AudioPlayer.player.start(audios);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, "Audio file not found!");
        }
        jLabel19.setText("Are you an elephant or what? Type a weight less than 500Kg.");
            runWeight(option);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
